version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: grewwnweez raw data source
    tables:
      - name: sales
        freshness: 
          warn_after: {count: 90, period: day}
        loaded_at_field: "CAST(..... as TIMESTAMP)"
        identifier: raw_gz_sales
        description: sales of greenweez / we have one row per products_id found eah orders_id.
        tests:
          - unique
          - not_null
        columns:
            - name: date_date
              description: date of purchase
      - name: product
        identifier: raw_gz_product
      - name: ship
        identifier: raw_gz_ship